name: Matrix Example

permissions:
   contents: read

on:
  workflow_dispatch:
  pull_request:
    paths: [standard/**, satellite/**, scripts/**, .github/workflows/main-staging.yaml]

env: 
  STYLES: '["standard", "satellite"]'

jobs:
  changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          matrix: true
          dir_names: true
          dir_names_exclude_current_dir: true
      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'

  deploy:
    name: Run deploy job
    runs-on: ubuntu-latest
    needs: [changed-files]
    if: needs.changed-files.outputs.matrix.any_changed == 'true'
    strategy:
      matrix: 
        files: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
      max-parallel: 4
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: |
          echo ${{ matrix.files }}
