name: Matrix Example

permissions:
   contents: read

on:
  workflow_dispatch:
  pull_request:
    paths: [standard/**, satellite/**, scripts/**, .github/workflows/main-staging.yaml]

env: 
  STYLES:  ["standard", "satellite"]

jobs:
  changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          matrix: true
          dir_names: true
      - name: Check if all values in STYLES are present
        id: check-styles
        run: |
          all_found=true
          for style in ${STYLES[@]}; do
            if [[ ! " ${changed-files[@]} " =~ " $style " ]]; then
              all_found=false
              break
            fi
          done
          echo "::set-output name=all_found::$all_found"
      - name: List changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'

  matrix-job:
    name: Run Matrix Job
    runs-on: ubuntu-latest
    needs: [check-styles]
    strategy:
      matrix: 
        files: ${{ fromJSON(needs.check-styles.outputs.matrix) }}
      max-parallel: 4
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: |
          echo ${{ matrix.files }}
