name: Styles test workflow

permissions:
   contents: read

on:
  pull_request:
    paths: [map-styles/**, scripts/**, .github/workflows/new-test-workflow.yaml]
  workflow_dispatch:

env: 
  STYLES: '["standard", "satellite", "mono"]'

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run tests
        run: |
          echo "test"
  changed-files:
    needs: test
    name: Get changed files
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          matrix: true
          dir_names: true
          dir_names_exclude_current_dir: true
      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'
        
