name: Styles test workflow

permissions:
   contents: read

on:
  pull_request:
    paths: [map-styles/**, scripts/**, .github/workflows/new-test-workflow.yaml]
  workflow_dispatch:

env:
  STYLES: '[standard, satellite, mono]'

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          matrix: true
          dir_names: true
          dir_names_exclude_current_dir: true
      
      - name: Debug changed files output
        run: |
          echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
          echo "Changed folders: ${{ steps.changed-files.outputs.all_changed_folders }}"
      
      - name: Extract unique folder names
        id: extract-folders
        run: |
          echo "${{ steps.changed-files.outputs.all_changed_files }}" | awk -F/ '{print $1}' | sort -u | tr '\n' ' ' > folders.txt
      
      - name: Read folder names from file
        run: |
          changed_folders=$(<folders.txt)
          echo "Changed folders: $changed_folders"
      
      - name: Check for style changes
        run: |
          STYLES=${{ toJson(env.STYLES) }}
          for folder in $changed_folders; do
            if [[ "$folder" == *"${STYLES}"* ]]; then
              echo "Changes detected in folder $folder, deploying..."
              exit 0
            fi
          done
          echo "No changes detected in relevant folders."

      - name: Check for script changes
        run: |
          STYLES=${{ toJson(env.STYLES) }}
          for folder in $changed_folders; do
            if [[ "$folder" == *"/scripts"* ]]; then
              for style in ${STYLES[@]}; do
                if [[ "$folder" == *"$style"* ]]; then
                  echo "Changes detected in folder $folder, deploying..."
                  exit 0
                fi
              done
            fi
          done
          echo "No changes detected in relevant folders."
