name: Styles test workflow

permissions:
   contents: read

on:
  pull_request:
    paths: [map-styles/**, scripts/**, .github/workflows/new-test-workflow.yaml]
  workflow_dispatch:

env:
  STYLES: '["standard", "satellite", "mono"]'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v44

      - name: Check for style changes
        run: |
          changed_folders=$(echo "${{ steps.changed_files.outputs.all_changed_folders }}" | tr '\n' ' ')
          for folder in $changed_folders; do
            if [[ "$folder" == *"${STYLES}"* ]]; then
              echo "Changes detected in folder $folder, deploying..."
              exit 0
            fi
          done
          echo "No changes detected in relevant folders."

      - name: Check for script changes
        run: |
          changed_folders=$(echo "${{ steps.changed_files.outputs.all_changed_folders }}" | tr '\n' ' ')
          for folder in $changed_folders; do
            if [[ "$folder" == *"/scripts"* ]]; then
              for style in ${STYLES[@]}; do
                if [[ "$folder" == *"$style"* ]]; then
                  echo "Changes detected in folder $folder, deploying..."
                  exit 0
                fi
              done
            fi
          done
          echo "No changes detected in relevant folders."
